### ISSUE TITLE
from Mnist.load_data import load_local_mnist

### ISSUE THREAD

**Issue by taojunhui** [datawhalechina/machine-learning-toy-code#2]
在看决策树的numpy实现，下问一下这是哪个依赖包
`from Mnist.load_data import load_local_mnist`

**Comment by johnjim0816** [comment]
> 在看决策树的numpy实现，下问一下这是哪个依赖包 `from Mnist.load_data import load_local_mnist`
这是之前版本实现的读取mnist函数，重新放在对应目录下了，或者直接用sklearn内置函数读取Mnist数据即可
